Add s3_prefix config option
ddebeau/zfs_uploader pull request #71
Opened 2023-07-11 22:47 UTC by jrothrock

Adds the ability to prefix s3 keys. This is useful if multiple hosts have similar named ZFS filesystems, but ultimately we want these backups to be going to the same bucket

2023-07-12 20:42 UTC, ddebeau requested changes
Thanks for the contribution! I agree, we should add a key prefix feature.

2023-07-12 20:42 UTC, ddebeau commented on README.md
> +#### s3_prefix : str, optional
Could you change the variable name to `prefix` so that it's inline with the other S3 parameters?

2023-07-12 20:42 UTC, ddebeau commented on tests/test_backup_db.py
> +        s3_key = derive_s3_key(f'{backup_time}.{backup_type}', self.filesystem,
Could you define `object_name` like you did for the tests above?

2023-07-12 20:42 UTC, ddebeau commented on zfs_uploader/job.py
> +        """ S3 key prefix. """
Could you make the variable description uniform across the README and object definitions?

2023-07-14 20:04 UTC, jrothrock commented
Certainly! Updated

2023-07-26 22:36 UTC, jrothrock commented
Sorry for the delay on this

2023-08-14 20:34 UTC, jrothrock commented
Looks like the tests may be failing due to missing secrets. I ran these with my own secrets and the tests passed

2023-08-16 19:46 UTC, merged