Use localstack to replace S3 dependency
ddebeau/zfs_uploader pull request #76
Opened 2024-01-02 04:35 UTC by rdelcorro

@ddebeau this removes the S3 dependency from tests and allows any fork to run the action without needing the secrets.

2024-01-07 17:03 UTC, ddebeau requested changes
Thanks for looking into this! I haven't used localstack before. Looks very cool.

2024-01-07 17:03 UTC, ddebeau commented on .github/workflows/test.yml
> +
Nit: Remove one newline

2024-01-07 17:03 UTC, ddebeau commented on .github/workflows/test.yml
> +
Nit: Remove newlines between steps

2024-01-07 17:08 UTC, ddebeau commented on .github/workflows/test.yml
> +        image: localstack/localstack
Could you switch the image to `localstack/localstack:s3-latest`? The image is much smaller than the standard one.

2024-01-08 02:58 UTC, rdelcorro commented
PR requested changes applied

2024-01-08 22:44 UTC, ddebeau approved these changes
Thanks!

2024-01-08 23:14 UTC, rdelcorro commented
I do not have write access to your repo, so you would have to merge. Thanks!

2024-01-09 01:38 UTC, merged